# -*- coding: utf-8 -*-
"""mymodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/<id>
"""

# !pip3 install -q tensorflow_gpu==2.1.0

import tensorflow as tf
print(tf.__version__)

# !pip3 install -q ktrain

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Code to read csv file into Colaboratory:
# !pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

id1 = ''

downloaded = drive.CreateFile({'id':id1}) 
downloaded.GetContentFile('data.csv')  
dataset = pd.read_csv('data.csv')

X = dataset.iloc[:,0].values
y = dataset.iloc[:,1].values

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
x_train
y_train

import ktrain
from ktrain import text
MODEL_NAME = 'distilbert-base-uncased'
t = text.Transformer(MODEL_NAME, maxlen=500, classes=y_train)
trn = t.preprocess_train(x_train, y_train)
val = t.preprocess_test(x_test, y_test)
model = t.get_classifier()
learner = ktrain.get_learner(model, train_data=trn, val_data=val, batch_size=6)

learner.fit_onecycle(5e-5, 4)

learner.validate(class_names=t.get_classes())

learner.view_top_losses(n=1, preproc=t)

print(x_test[371])

predictor = ktrain.get_predictor(learner.model, preproc=t)

predictor.predict('itching  nodal_skin_eruptions  dischromic _patches')

# predicted probability scores for each category
predictor.predict_proba('itching  nodal_skin_eruptions  dischromic _patches')

predictor.get_classes()

# !pip3 install -q git+https://github.com/amaiya/eli5@tfkeras_0_10_1

predictor.explain('itching  nodal_skin_eruptions  dischromic _patches')

predictor.save('/tmp/my_distilbert_predictor')

reloaded_predictor = ktrain.load_predictor('/tmp/my_distilbert_predictor')

reloaded_predictor.predict('itching  skin_rash  dischromic _patches')

